// <auto-generated />
using IndividuellAngular.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndividuellAngular.Migrations
{
    [DbContext(typeof(KundeServiceContext))]
    [Migration("20191117182654_NewestDB")]
    partial class NewestDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IndividuellAngular.Models.FAQ", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("downvote")
                        .HasColumnType("int");

                    b.Property<int>("kategoriId")
                        .HasColumnType("int");

                    b.Property<string>("sporsmal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("svar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("upvote")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("kategoriId");

                    b.ToTable("AlleFaq");

                    b.HasData(
                        new
                        {
                            id = 1,
                            downvote = 0,
                            kategoriId = 1,
                            sporsmal = "Hvordan kjøper jeg billett?",
                            svar = "Du kan kjøpe billett fra: Vy.no, Vy appen, billettautomat, betjent stasjon, narvesen, om bord i toget og hos kundeservice.",
                            upvote = 0
                        },
                        new
                        {
                            id = 2,
                            downvote = 0,
                            kategoriId = 1,
                            sporsmal = "Hvordan kjøper jeg periodebillett?",
                            svar = "Det enkleste for deg er å kjøpe periodebilletten i appen. Du kan ikke kjøpre periodebillett om bord.",
                            upvote = 0
                        },
                        new
                        {
                            id = 3,
                            downvote = 0,
                            kategoriId = 1,
                            sporsmal = "Hva er reisekort?",
                            svar = "Med reisekort reiser du med elektronisk billett hos Vy og Ruter, som samarbeider om kortsystemet elektronisk reisekort. Reisekortet gjelder i Oslo og Akershus. Du kan kjøpe reisekort fra kundeservice eller på betjent stasjon.",
                            upvote = 0
                        },
                        new
                        {
                            id = 4,
                            downvote = 0,
                            kategoriId = 2,
                            sporsmal = "Hvordan kan jeg endre eller avbestille billetten?",
                            svar = "For å endre billetten din, må du først avbestille den og så kjøpe ny billett til avgangen du skal reise med.",
                            upvote = 0
                        },
                        new
                        {
                            id = 5,
                            downvote = 0,
                            kategoriId = 2,
                            sporsmal = "Hvordan endrer jeg navn på billetten?",
                            svar = "Når du kjøper billetter så er det navnet til den som bestiller som står på billettene. Det er altså ikke noe i veien for at det står samme navn på flere billetter, så lenge personen som bestilte billettene skal være med på reisen. Hvis ikke personen står som oppført på billettene blir med på reisen, ring eller chat med kundeservice for å endre navn.",
                            upvote = 0
                        },
                        new
                        {
                            id = 6,
                            downvote = 0,
                            kategoriId = 3,
                            sporsmal = "Jeg har glemt noe om bord. Hvordan kontakter jeg dere om hittegods?",
                            svar = "Dersom du har glemt noe om bord kan du kontakte kundeservice som vil videreføre deg til hittegodskontoret som passer deg. Her vil en ansatt kunne svare på om det du har mistet har ankommet hittegodskontoret.",
                            upvote = 0
                        },
                        new
                        {
                            id = 7,
                            downvote = 0,
                            kategoriId = 3,
                            sporsmal = "Hvor mye bagasje kan jeg ha med?",
                            svar = "Du kan ta med deg inntil 30 kilo fordelt på maksimum 3 kolli. Har du mer enn dette og skal reise mellom Oslo og Voss/Bergen eller Trondheim, kan du benytte deg av bagasjetransport.",
                            upvote = 0
                        });
                });

            modelBuilder.Entity("IndividuellAngular.Models.InnSporsmal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sporsmal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AlleInnSporsmal");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "fredrik1998@hotmail.com",
                            navn = "Fredrik Riise",
                            sporsmal = "Dersom toget blir innstilt, dekkes taxi av dere?"
                        },
                        new
                        {
                            id = 2,
                            email = "per.persen@gmail.com",
                            navn = "Per Persen",
                            sporsmal = "Hvem kontakter jeg dersom jeg har mistet noe på toget deres?"
                        },
                        new
                        {
                            id = 3,
                            email = "karoline.m95@gmail.com",
                            navn = "Karoline Martinsen",
                            sporsmal = "Jeg hadde billett, men fikk fortsatt bot. Hvordan kan jeg klage?"
                        });
                });

            modelBuilder.Entity("IndividuellAngular.Models.Kategori", b =>
                {
                    b.Property<int>("kategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kategoriNavn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kategoriId");

                    b.ToTable("AlleKategorier");

                    b.HasData(
                        new
                        {
                            kategoriId = 1,
                            kategoriNavn = "Billetter"
                        },
                        new
                        {
                            kategoriId = 2,
                            kategoriNavn = "Endringer"
                        },
                        new
                        {
                            kategoriId = 3,
                            kategoriNavn = "Bagasje og kjæledyr"
                        });
                });

            modelBuilder.Entity("IndividuellAngular.Models.FAQ", b =>
                {
                    b.HasOne("IndividuellAngular.Models.Kategori", "kategoriNavn")
                        .WithMany()
                        .HasForeignKey("kategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
